-- Derivation Config Versions (Unified Schema)
-- Phase: prep (graph algorithms), generate (LLM derivation), refine (validation/improvement)
-- Sequence determines execution order within each phase

-- =============================================================================
-- PREP PHASE: Graph algorithms that filter/prepare nodes before LLM derivation
-- =============================================================================

-- k-core filter: Remove low-connectivity nodes (noise reduction)
INSERT INTO derivation_config (id, step_name, phase, version, sequence, enabled, llm, input_graph_query, params, is_active) VALUES (1, 'k_core_filter', 'prep', 1, 1, TRUE, FALSE, 'MATCH (n:Graph) OPTIONAL MATCH (n)-[r]-() WITH n, count(r) as degree RETURN n, degree', '{"k": 2, "description": "Remove nodes with degree < k"}', TRUE);

-- SCC cycle detection: Identify strongly connected components
INSERT INTO derivation_config (id, step_name, phase, version, sequence, enabled, llm, input_graph_query, params, is_active) VALUES (2, 'scc_detection', 'prep', 1, 2, FALSE, FALSE, 'MATCH (n:Graph)-[r]->(m:Graph) RETURN n, r, m', '{"min_size": 2, "description": "Detect strongly connected components"}', TRUE);

-- Louvain community detection: Group related nodes into communities
INSERT INTO derivation_config (id, step_name, phase, version, sequence, enabled, llm, input_graph_query, params, is_active) VALUES (3, 'louvain_communities', 'prep', 1, 3, FALSE, FALSE, 'MATCH (n:Graph)-[r]->(m:Graph) RETURN n, r, m', '{"resolution": 1.0, "description": "Detect communities using Louvain algorithm"}', TRUE);

-- Articulation points: Find critical nodes that bridge components
INSERT INTO derivation_config (id, step_name, phase, version, sequence, enabled, llm, input_graph_query, params, is_active) VALUES (4, 'articulation_points', 'prep', 1, 4, FALSE, FALSE, 'MATCH (n:Graph)-[r]-(m:Graph) RETURN n, r, m', '{"mark_critical": true, "description": "Identify articulation points (bridge nodes)"}', TRUE);

-- PageRank: Calculate node importance/significance
INSERT INTO derivation_config (id, step_name, phase, version, sequence, enabled, llm, input_graph_query, params, is_active) VALUES (5, 'pagerank', 'prep', 1, 5, TRUE, FALSE, 'MATCH (n:Graph)-[r]->(m:Graph) RETURN n, r, m', '{"damping": 0.85, "iterations": 20, "description": "Calculate node significance via PageRank"}', TRUE);

-- =============================================================================
-- GENERATE PHASE: LLM-based element derivation from graph nodes
-- =============================================================================

-- Application Layer Elements
INSERT INTO derivation_config (id, step_name, phase, version, sequence, enabled, llm, input_graph_query, instruction, example, is_active) VALUES (101, 'ApplicationComponent', 'generate', 1, 1, TRUE, TRUE, 'MATCH (d:Graph:Directory) WHERE d.path STARTS WITH ''src/'' AND d.active = true RETURN d', 'Group top-level code directories into ApplicationComponents. Use directory name as component name, include repo for context. Avoid nesting unless clear submodules exist.', '{"identifier":"app-comp:auth","name":"Auth Component","layer":"Application","source":"Directory:src/auth","confidence":0.8}', TRUE);

INSERT INTO derivation_config (id, step_name, phase, version, sequence, enabled, llm, input_graph_query, instruction, example, is_active) VALUES (102, 'ApplicationService', 'generate', 1, 2, TRUE, TRUE, 'MATCH (t:Graph:TypeDefinition)-[:HAS_METHOD]->(m:Graph:Method) WHERE t.active = true RETURN t,m', 'Derive ApplicationServices from service-like types (for example *Service or *Manager). Aggregate public methods into one service and name service after the type.', '{"identifier":"svc:auth","name":"Authentication Service","operations":["login","logout"],"servedBy":"ApplicationComponent:Auth Component","confidence":0.8}', TRUE);

INSERT INTO derivation_config (id, step_name, phase, version, sequence, enabled, llm, input_graph_query, instruction, example, is_active) VALUES (103, 'ApplicationInterface', 'generate', 1, 3, TRUE, TRUE, 'MATCH (f:Graph:File) WHERE f.fileType=''source'' AND f.subtype IN [''python'',''javascript'',''typescript''] AND f.active = true RETURN f', 'Identify externally exposed interfaces (REST, gRPC, CLI). Prefer files declaring routes or endpoints or RPC definitions. Summarize protocol and endpoint root.', '{"identifier":"if:rest","name":"REST API","protocol":"HTTP","endpoint":"/api","exposes":["POST /login","POST /logout"],"confidence":0.7}', TRUE);

INSERT INTO derivation_config (id, step_name, phase, version, sequence, enabled, llm, input_graph_query, instruction, example, is_active) VALUES (104, 'DataObject', 'generate', 1, 4, TRUE, TRUE, 'MATCH (t:Graph:TypeDefinition) WHERE t.category=''class'' AND t.active = true RETURN t', 'Create DataObjects from data-centric types (entities, DTOs, schemas). Include key fields only and omit behaviors.', '{"identifier":"do:user","name":"User","schema":{"id":"int","email":"string"},"source":"TypeDefinition:User","confidence":0.75}', TRUE);

-- Business Layer Elements
INSERT INTO derivation_config (id, step_name, phase, version, sequence, enabled, llm, input_graph_query, instruction, example, is_active) VALUES (105, 'BusinessProcess', 'generate', 1, 5, FALSE, TRUE, 'MATCH (b:Graph:BusinessConcept) WHERE b.conceptType=''process'' AND b.active = true RETURN b', 'Map domain-level processes to BusinessProcess elements. Use business naming and include a one-line outcome.', '{"identifier":"bp:onboarding","name":"User Onboarding","outcome":"Activated user account","confidence":0.6}', TRUE);

INSERT INTO derivation_config (id, step_name, phase, version, sequence, enabled, llm, input_graph_query, instruction, example, is_active) VALUES (106, 'BusinessObject', 'generate', 1, 6, TRUE, TRUE, 'MATCH (t:Graph:TypeDefinition) WHERE t.category=''class'' AND t.name CONTAINS ''Entity'' AND t.active = true RETURN t', 'Map business domain entities to BusinessObject elements. Focus on domain concepts rather than technical data structures. Include key business attributes.', '{"identifier":"bo:customer","name":"Customer","attributes":["customerId","name","status"],"source":"TypeDefinition:Customer","confidence":0.7}', TRUE);

INSERT INTO derivation_config (id, step_name, phase, version, sequence, enabled, llm, input_graph_query, instruction, example, is_active) VALUES (107, 'BusinessFunction', 'generate', 1, 7, FALSE, TRUE, 'MATCH (b:Graph:BusinessConcept) WHERE b.conceptType=''function'' AND b.active = true RETURN b', 'Identify business functions from domain concepts. Group related business behaviors by capability or responsibility area.', '{"identifier":"bf:payment","name":"Payment Processing","description":"Handles all payment-related operations","confidence":0.65}', TRUE);

INSERT INTO derivation_config (id, step_name, phase, version, sequence, enabled, llm, input_graph_query, instruction, example, is_active) VALUES (108, 'BusinessEvent', 'generate', 1, 8, FALSE, TRUE, 'MATCH (b:Graph:BusinessConcept) WHERE b.conceptType=''event'' AND b.active = true RETURN b', 'Map domain events to BusinessEvent elements. Focus on state changes that trigger business processes or decisions.', '{"identifier":"be:order-placed","name":"Order Placed","trigger":"Customer completes checkout","confidence":0.6}', TRUE);

INSERT INTO derivation_config (id, step_name, phase, version, sequence, enabled, llm, input_graph_query, instruction, example, is_active) VALUES (109, 'BusinessActor', 'generate', 1, 9, FALSE, TRUE, 'MATCH (b:Graph:BusinessConcept) WHERE b.conceptType=''actor'' AND b.active = true RETURN b', 'Identify business actors from domain concepts. Include roles, departments, or external parties that perform business behaviors.', '{"identifier":"ba:customer","name":"Customer","type":"external","responsibilities":["Place orders","Make payments"],"confidence":0.7}', TRUE);

-- Technology Layer Elements
INSERT INTO derivation_config (id, step_name, phase, version, sequence, enabled, llm, input_graph_query, instruction, example, is_active) VALUES (110, 'TechnologyService', 'generate', 1, 10, TRUE, TRUE, 'MATCH (e:Graph:ExternalDependency) WHERE e.active = true RETURN e', 'Represent external platforms and services (DBs, queues, frameworks) as TechnologyService. Prefer vendor plus product naming and include version when known.', '{"identifier":"tech:postgres","name":"PostgreSQL","category":"database","version":"15","confidence":0.9}', TRUE);

INSERT INTO derivation_config (id, step_name, phase, version, sequence, enabled, llm, input_graph_query, instruction, example, is_active) VALUES (111, 'Node', 'generate', 1, 11, FALSE, TRUE, 'MATCH (e:Graph:ExternalDependency) WHERE e.category=''infrastructure'' AND e.active = true RETURN e', 'Map infrastructure resources to Node elements. Include servers, containers, cloud resources that host or execute software.', '{"identifier":"node:app-server","name":"Application Server","type":"virtual","platform":"AWS EC2","confidence":0.75}', TRUE);

INSERT INTO derivation_config (id, step_name, phase, version, sequence, enabled, llm, input_graph_query, instruction, example, is_active) VALUES (112, 'Device', 'generate', 1, 12, FALSE, TRUE, 'MATCH (e:Graph:ExternalDependency) WHERE e.category=''hardware'' AND e.active = true RETURN e', 'Identify physical devices from dependencies. Focus on hardware resources like servers, network equipment, or IoT devices.', '{"identifier":"dev:load-balancer","name":"Load Balancer","type":"network","vendor":"F5","confidence":0.8}', TRUE);

INSERT INTO derivation_config (id, step_name, phase, version, sequence, enabled, llm, input_graph_query, instruction, example, is_active) VALUES (113, 'SystemSoftware', 'generate', 1, 13, TRUE, TRUE, 'MATCH (e:Graph:ExternalDependency) WHERE e.category IN [''runtime'',''platform''] AND e.active = true RETURN e', 'Map system software and platforms to SystemSoftware elements. Include runtimes, operating systems, middleware, and platform services.', '{"identifier":"sys:nodejs","name":"Node.js Runtime","version":"18.x","category":"runtime","confidence":0.85}', TRUE);

-- =============================================================================
-- REFINE PHASE: Validation and improvement of derived model
-- =============================================================================

-- Completeness Validation: Ensure significant nodes have corresponding elements
INSERT INTO derivation_config (id, step_name, phase, version, sequence, enabled, llm, input_graph_query, input_model_query, instruction, example, is_active) VALUES (201, 'Completeness', 'refine', 1, 1, TRUE, TRUE, 'MATCH (n:Graph) WHERE n.significance > 0.5 AND n.active = true RETURN n', 'MATCH (e:Model) RETURN e', 'Compare graph nodes with ArchiMate elements. Identify graph nodes with high significance (>0.5) that don''t have corresponding ArchiMate elements. For each missing element, suggest creating an appropriate ArchiMate element with proper type, name, and relationships. Return an array of new elements to add with their confidence scores.', '{"new_elements":[{"identifier":"ac:payment-processor","type":"ApplicationComponent","name":"Payment Processor","source_node":"Graph:PaymentService","reason":"High-significance service node without ArchiMate representation","confidence":0.85}],"new_relationships":[]}', TRUE);

-- Relationship Consistency: Verify graph relationships are reflected in model
INSERT INTO derivation_config (id, step_name, phase, version, sequence, enabled, llm, input_graph_query, input_model_query, instruction, example, is_active) VALUES (202, 'RelationshipConsistency', 'refine', 1, 2, TRUE, TRUE, 'MATCH (source:Graph)-[r]->(target:Graph) WHERE source.significance > 0.3 AND target.significance > 0.3 AND source.active = true AND target.active = true RETURN source, type(r) as rel_type, target', 'MATCH (source:Model)-[r]->(target:Model) RETURN source, type(r) as rel_type, target', 'Compare relationships between graph nodes and ArchiMate elements. Identify missing or incorrect relationships in the ArchiMate model. For each discrepancy, suggest adding or updating relationships using appropriate ArchiMate relationship types (Composition, Aggregation, Serving, Realization, Access, Flow). Ensure relationship types follow ArchiMate metamodel rules. Return arrays of new and updated relationships.', '{"new_elements":[],"new_relationships":[{"source":"ac:api-gateway","target":"as:user-service","type":"Serving","reason":"Graph shows API Gateway calls User Service, missing in ArchiMate","confidence":0.9}],"updated_relationships":[{"source":"ac:database","target":"do:user-data","old_type":"Composition","new_type":"Access","reason":"Database accesses data, not composes it","confidence":0.85}]}', TRUE);

-- Layering & Abstraction: Ensure proper ArchiMate layering
INSERT INTO derivation_config (id, step_name, phase, version, sequence, enabled, llm, input_graph_query, input_model_query, instruction, example, is_active) VALUES (203, 'LayeringAbstraction', 'refine', 1, 3, FALSE, TRUE, 'MATCH (n:Graph) WHERE n.active = true RETURN n, labels(n) as node_labels, n.category as category', 'MATCH (e:Model) RETURN e, e.type as element_type, e.layer as layer', 'Analyze the ArchiMate model for proper layering and abstraction. Check: 1) Elements are in correct layers (Business/Application/Technology), 2) Abstraction levels are appropriate (not too technical in business layer, not too abstract in technology layer), 3) Cross-layer relationships follow ArchiMate patterns. Suggest reclassifying elements or splitting/merging elements to improve architectural clarity. Return arrays of reclassified elements, split suggestions, and new relationships.', '{"reclassified_elements":[{"identifier":"ac:user-authentication","current_type":"ApplicationComponent","suggested_type":"ApplicationService","reason":"Represents behavior/capability, not a structural component","confidence":0.8}],"split_suggestions":[{"identifier":"ac:monolith-app","suggested_elements":[{"type":"ApplicationComponent","name":"User Management Module"},{"type":"ApplicationComponent","name":"Order Processing Module"},{"type":"ApplicationComponent","name":"Inventory Module"}],"reason":"Large monolithic component should be decomposed for clarity","confidence":0.7}],"new_relationships":[]}', TRUE);
