"""ArchiMate XML Export - Export ArchiMate models to XML format.

This module provides functionality to export ArchiMate models to the
Open Group ArchiMate Exchange Format (XML), compatible with Archi tool.

Reference: https://www.opengroup.org/archimate-forum/archimate-exchange-format
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from lxml import etree  # type: ignore[import-untyped]

from .models import Element, Relationship


class ArchiMateXMLExporter:
    """Export ArchiMate models to XML format."""

    # ArchiMate 3.0 namespace
    ARCHIMATE_NS = "http://www.opengroup.org/xsd/archimate/3.0/"
    DC_NS = "http://purl.org/dc/elements/1.1/"
    XSI_NS = "http://www.w3.org/2001/XMLSchema-instance"
    XML_NS = "http://www.w3.org/XML/1998/namespace"

    NSMAP = {None: ARCHIMATE_NS, "xsi": XSI_NS, "dc": DC_NS}

    SCHEMA_LOCATION = (
        "http://www.opengroup.org/xsd/archimate/3.0/ "
        "http://www.opengroup.org/xsd/archimate/3.1/archimate3_Model.xsd"
    )

    def __init__(self, pretty_print: bool = True, encoding: str = "UTF-8"):
        """
        Initialize XML exporter.

        Args:
            pretty_print: If True, format XML with indentation
            encoding: XML encoding (default UTF-8)
        """
        self.pretty_print = pretty_print
        self.encoding = encoding

    def export(
        self,
        elements: list[Element],
        relationships: list[Relationship],
        output_path: str,
        model_name: str = "ArchiMate Model",
        model_id: str = "model-001",
    ) -> None:
        """
        Export ArchiMate model to XML file.

        Args:
            elements: List of ArchiMate elements
            relationships: List of ArchiMate relationships
            output_path: Path to output XML file
            model_name: Name of the model
            model_id: Unique identifier for the model
        """
        # Create root model element
        root = etree.Element(
            "model",
            nsmap=self.NSMAP,
            attrib={
                "identifier": model_id,
                f"{{{self.XSI_NS}}}schemaLocation": self.SCHEMA_LOCATION,
            },
        )

        # Add model name with xml:lang attribute
        name_elem = etree.SubElement(root, "name")
        name_elem.set(f"{{{self.XML_NS}}}lang", "en")
        name_elem.text = model_name

        # Add metadata
        self._add_metadata(root)

        # Add elements section
        if elements:
            elements_section = etree.SubElement(root, "elements")
            for element in elements:
                self._add_element(elements_section, element)

        # Add relationships section
        if relationships:
            rels_section = etree.SubElement(root, "relationships")
            for relationship in relationships:
                self._add_relationship(rels_section, relationship)

        # Write to file
        tree = etree.ElementTree(root)
        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)

        tree.write(
            str(output_file),
            pretty_print=self.pretty_print,
            xml_declaration=True,
            encoding=self.encoding,
        )

    def _add_metadata(self, root: etree.Element) -> None:
        """Add metadata to model root."""
        metadata = etree.SubElement(root, "metadata")

        # Add schema info
        schema = etree.SubElement(metadata, "schema")
        schema.text = "Dublin Core"

        schemaversion = etree.SubElement(metadata, "schemaversion")
        schemaversion.text = "1.1"

        # Add Dublin Core elements
        title = etree.SubElement(metadata, f"{{{self.DC_NS}}}title")
        title.text = "Deriva Generated Model"

        creator = etree.SubElement(metadata, f"{{{self.DC_NS}}}creator")
        creator.text = "Deriva"

        date = etree.SubElement(metadata, f"{{{self.DC_NS}}}date")
        date.text = datetime.now().strftime("%Y-%m-%d")

        description = etree.SubElement(metadata, f"{{{self.DC_NS}}}description")
        description.text = (
            "ArchiMate model generated by Deriva from source code analysis"
        )

    def _add_element(self, parent: etree.Element, element: Element) -> None:
        """
        Add an element to the XML tree.

        Args:
            parent: Parent XML element
            element: ArchiMate element to add
        """
        elem = etree.SubElement(
            parent,
            "element",
            attrib={
                "identifier": element.identifier,
                f"{{{self.XSI_NS}}}type": element.element_type,
            },
        )

        # Add name with xml:lang
        name_elem = etree.SubElement(elem, "name")
        name_elem.set(f"{{{self.XML_NS}}}lang", "en")
        name_elem.text = element.name

        # Add documentation if present
        if element.documentation:
            doc_elem = etree.SubElement(elem, "documentation")
            doc_elem.set(f"{{{self.XML_NS}}}lang", "en")
            doc_elem.text = element.documentation

        # Note: Properties are not exported as they require propertyDefinitions
        # at the model level per ArchiMate Exchange Format XSD.
        # Internal metadata (source, confidence, derived_at) is omitted.

    def _add_relationship(
        self, parent: etree.Element, relationship: Relationship
    ) -> None:
        """
        Add a relationship to the XML tree.

        Args:
            parent: Parent XML element
            relationship: ArchiMate relationship to add
        """
        rel = etree.SubElement(
            parent,
            "relationship",
            attrib={
                "identifier": relationship.identifier,
                f"{{{self.XSI_NS}}}type": relationship.relationship_type,
                "source": relationship.source,
                "target": relationship.target,
            },
        )

        # Add name if present
        if relationship.name:
            name_elem = etree.SubElement(rel, "name")
            name_elem.text = relationship.name

        # Add documentation if present
        if relationship.documentation:
            doc_elem = etree.SubElement(rel, "documentation")
            doc_elem.text = relationship.documentation

        # Note: Properties are not exported as they require propertyDefinitions
        # at the model level per ArchiMate Exchange Format XSD.

    def export_to_string(
        self,
        elements: list[Element],
        relationships: list[Relationship],
        model_name: str = "ArchiMate Model",
        model_id: str = "model-001",
    ) -> str:
        """
        Export ArchiMate model to XML string.

        Args:
            elements: List of ArchiMate elements
            relationships: List of ArchiMate relationships
            model_name: Name of the model
            model_id: Unique identifier for the model

        Returns:
            XML string
        """
        # Create root model element
        root = etree.Element(
            "model",
            nsmap=self.NSMAP,
            attrib={"identifier": model_id, "version": "5.0.0"},
        )

        # Add model name
        name_elem = etree.SubElement(root, "name")
        name_elem.text = model_name

        # Add metadata
        self._add_metadata(root)

        # Add elements section
        if elements:
            elements_section = etree.SubElement(root, "elements")
            for element in elements:
                self._add_element(elements_section, element)

        # Add relationships section
        if relationships:
            rels_section = etree.SubElement(root, "relationships")
            for relationship in relationships:
                self._add_relationship(rels_section, relationship)

        # Return as string
        return etree.tostring(
            root,
            pretty_print=self.pretty_print,
            xml_declaration=True,
            encoding=self.encoding,
        ).decode(self.encoding)
